spring:
  application:
    name: movies
  datasource:
    url: jdbc:h2:file:./.generated/database;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: user
    password: a_strong_password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
